######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 7 14:11:38 2011
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += tests.cpp
